
PATCH http://localhost:3000/task/complete/51

###
GET http://localhost:3000/list/fetch/3

###
GET http://localhost:3000/list/delete/1

###
GET http://localhost:3000/task/open/37

###
POST http://localhost:3000/task/create
Content-Type: application/json

{
  "title": "Estudar Node.js",
  "description": "Ler documentação e fazer exercícios",
  "dueDate": "2025-09-10",
  "taskListId": 1
}

###
POST http://localhost:3000/list/add
Content-Type: application/json

{
  "title": "Estudar Java",
  "description": "Ler documentação e fazer exercícios",
  "dueDate": "2025-09-10",
  "taskListId": 4
}

###
POST http://localhost:3000/list/create
Content-Type: application/json

{
  "title": "Tarefas de Estudo",
  "userId": 2
}

###
POST http://localhost:3000/list/rename
Content-Type: application/json

{
  "taskListId": 2,
  "title": "Estudar sexo"
}

###
POST http://localhost:3000/list/remove
Content-Type: application/json

{
  "taskId": 36,
  "taskListId": 2
  
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "bolsonaro@gmail.com",
  "password": "12345"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "bolsonaro@gmail.com",
  "password": "12345"
}

###
POST http://localhost:3000/auth/logout
Content-Type: application/json
{}

###DELETE http://localhost:3000/task/deleteTask
Content-Type: application/json

{
  "taskId": 2
}

###
GET http://localhost:3000/task/fetchSteps/1

###
GET http://localhost:3000/list/user/2



